### ISSUE TITLE
Support for in-memory storage

### ISSUE THREAD

**Issue by Tochemey** [shaj13/raft#11]

**Comment by shaj13** [comment]
@Tochemey whats this issue for, the title can't describe a feature request please provide the current behavior and what you would like to see

**Comment by Tochemey** [comment]
@shaj13 This is not an issue. I am just asking whether instead durable raft state, we should also provide an in-memory raft state because there may be some use cases where in-memory state is sufficient without the need of a filesystem

**Comment by shaj13** [comment]
> @shaj13 This is not an issue. I am just asking whether instead durable raft state, we should also provide an in-memory raft state because there may be some use cases where in-memory state is sufficient without the need of a filesystem

working on something similar, right now its under review, will update the issue accordingly
