### ISSUE TITLE
Remove dead node

### ISSUE THREAD

**Issue by kotyara85** [shaj13/raft#22]
Is it possible to remove dead node from the cluster?
RemoveMember seems to be just marking node as removed
Thanks

**Comment by shank318** [comment]
@shaj13 Please check this. The problem is that in my k8s deployment, I am using RemoveNode before scaling down the pods running in the cluster but when I scale up again, sometimes the pod is assigned the same IP as the removed node and this is where it fails saying that address already in use.

**Comment by shaj13** [comment]
Fixed: We now allow reusing the address if a member has been removed. However, we do not allow the members to reuse IDs by design. Therefore, when scaling up and down, if member IDs are not changed, an error will be returned, and the leader will refuse to add the member to the cluster.
