### ISSUE TITLE
example cannot work under http protocol

### ISSUE THREAD

**Issue by franklee0817** [shaj13/raft#4]
I found there's a critical error in `transport.Dialer` while using `transport.HTTP` instead of `transport.GRPC`. The address parameter is like `127.0.0.1:8080`. `rafthttp.Dialer` while pass this address to `rafthttp.client` thus problems will happen when the leader is trying to communicate with followers. `rafthttp.client.Message` proceed client request via `http.NewRequestWithContext` in `rafthttp.client.requestProto` method. Because the scheme of URL is missing from which we passed (127.0.0.1:8080) in the dialer. 

More detail please see net/url.Parse.  URL schema is required.

**Comment by franklee0817** [comment]
bug was found in _examples/raft

**Comment by shaj13** [comment]
@franklee0817 the caller must start the server for both http and grpc protocols, therefore the caller must set the scheme. 
Pass http://127.0.0.1:8080 as address should do the work. 
Feel free to re-open
