### ISSUE TITLE
Log is being applied on restart

### ISSUE THREAD

**Issue by kotyara85** [shaj13/raft#7]
Hello,
Is it an expected behavior?
After a node is restarted I see it fetches all the data from the leader
I'd expect it to get only the diff
Thanks

**Comment by shaj13** [comment]
@kotyara85 depends on the node state, if when it restarted it lost durable storage then the leader will send out all logs again if there was a snapshot the leader will not send a diff it will send out a snapshot instead. 

what was the term and index of the node before and after restart?

**Comment by kotyara85** [comment]
@shaj13 sorry for the late reply, apply triggers on the local node and doesn't seem like affecting other nodes in the cluster. Does that mean I should somehow keep latest index and ignore all updates?
Thanks

**Comment by kotyara85** [comment]
Oh, And how do I get a current index? Doesn't seem like there's any interfaces on the node object which allow to fetch taht
Thanks

**Comment by kotyara85** [comment]
Ok, i figured out the snapshot situation
@shaj13 is there a way to notify if a current node was elected as a leader?
Thanks

**Comment by shaj13** [comment]
@kotyara85  

Great to know, can you tell what was the issue with snapshot situation ? 

you can do the following to check if current node is leader: 
```go
func IsLeader(n *raft.Node) bool {
retrun n.Whoami() == n.Leader()
}
```
as well you can wrap it with a time.Ticker to report to a chan when its promoted to be a leader.
