### ISSUE TITLE
Production fitness

### ISSUE THREAD

**Issue by Tochemey** [shaj13/raft#9]
Hello @shaj13 

Thanks for this great library. It has helped a lot understanding the etcd raft. However I would like to know whether this library has been used in production already.

**Comment by shaj13** [comment]
@Tochemey  yup, its ran in a cloud production with gRPC transport layer. 
we have examined and investigated large projects like [docker-swarm](https://github.com/moby/swarmkit/tree/master/manager/state/raft) [etcd](https://github.com/etcd-io/etcd/tree/main/server/etcdserver/api/rafthttp) [cockroach db](https://github.com/cockroachdb/cockroach/tree/master/pkg/kv/kvserver) before coming with this library.
